sudo: false
language: go
go:
  - "1.17"
  - "1.18"

install:
  - go get google.golang.org/grpc
  - go get golang.org/x/net/context
  - go get github.com/stretchr/testify

script:
 - go test -race -v ./...
